### ISSUE TITLE
opt: dEQP-VK.graphicsfuzz.do-while-with-always-true-if

### ISSUE THREAD

**Issue by paulthomson** [KhronosGroup/SPIRV-Tools#3034] opened 2019-11-11 21:41 UTC
This test fails. To reproduce: 

```
spirv-opt -O -o temp.spv *.spv
spirv-val temp.spv
```

[do-while-with-always-true-if.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/3833328/do-while-with-always-true-if.zip)

**Comment by s-perron** [comment] 2019-11-19 02:28
Duplicate of #3030.

**Closed by s-perron** 2019-11-19 02:28 UTC
