### ISSUE TITLE
SmallVector operator== cause infinite recursion (clang)

### ISSUE THREAD

**Issue by Retr111** [KhronosGroup/SPIRV-Tools#4481] opened 2021-08-19 05:25 UTC
Both XCode(Apple clang version 12.0.5) and Android Studio have this problem。

1. RegisterPass, `spvtools::CreateSetSpecConstantDefaultValuePass`
2. Infinite recursion in `operator==(const std::vector<T>& lhs, const SmallVector& rhs)`

```
# set_spec_constant_default_value_pass.cpp
# line 282
# https://github.com/KhronosGroup/SPIRV-Tools/blob/1ad8b71359b27835c9682dbcf6ef152fe14cd473/source/opt/set_spec_constant_default_value_pass.cpp
     
        if (spec_inst->GetInOperand(kOpSpecConstantLiteralInOperandIndex)
                .words != bit_pattern) {
```

```
# small_vector.h
# line 178
# https://github.com/KhronosGroup/SPIRV-Tools/blob/1ad8b71359b27835c9682dbcf6ef152fe14cd473/source/util/small_vector.h

  friend bool operator==(const std::vector<T>& lhs, const SmallVector& rhs) {
    return rhs == lhs;
  }

  friend bool operator!=(const SmallVector& lhs, const std::vector<T>& rhs) {
    return !(lhs == rhs);
  }

```

**Comment by s-perron** [comment] 2022-03-02 15:24
Is this fixed by https://github.com/KhronosGroup/SPIRV-Tools/pull/4681?  I'll assume it is.  I cannot reproduce this myself to double check.

**Closed by s-perron** 2022-03-02 15:24 UTC
