### ISSUE TITLE
opt: dEQP-VK.graphicsfuzz.discard-in-loop-in-function

### ISSUE THREAD

**Issue by paulthomson** [KhronosGroup/SPIRV-Tools#3032] opened 2019-11-11 21:38 UTC
This test fails. To reproduce: 

```
spirv-opt -O -o temp.spv *.spv
spirv-val temp.spv
```

[discard-in-loop-in-function.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/3833318/discard-in-loop-in-function.zip)

**Comment by s-perron** [comment] 2019-11-19 02:24
Duplicate of #3031.

**Closed** 2019-11-19 02:24 UTC
