### ISSUE TITLE
spirv-opt --convert-relaxed-to-half and OpConstant

### ISSUE THREAD

**Issue by sivu** [KhronosGroup/SPIRV-Tools#4946] opened 2022-09-23 20:13 UTC
Running spirv-opt --convert-relaxed-to-half removes RelaxedPrecision decoration from OpConstant types. 

This seems like a bug, because OpConstant is not modified by the relaxed-to-half conversion.

**Comment by s-perron** [comment] 2023-03-29 17:09
FYI @greg-lunarg

**Comment by greg-lunarg** [comment] 2023-03-29 17:55
The purpose of this pass is to create optimal SPIR-V for platforms that support half-precision but do not support relaxed precision. The relaxed decorations are removed because by definition they are not needed.

I guess if you can make a case for a similar pass where the relaxed precision decorations are not removed, the maintainers would at least consider allowing someone to implement it.

Since I think I have explained why this is not a bug, I will close this. Please open a feature request issue if you wish.

**Closed** 2023-03-29 17:55 UTC
Labels: bug

**Comment by s-perron** [comment] 2023-03-29 18:37
Without an example, I cannot tell what is going on. Does the type of the OpConstant get changed to half precision? If not, should it be? The issue says "OpConstant is not modified by the relaxed-to-half conversion".

**Comment by greg-lunarg** [comment] 2023-03-29 20:58
@s-perron Ah. Good catch. I only read the first statement: Running spirv-opt --convert-relaxed-to-half removes RelaxedPrecision decoration from OpConstant types. As I stated above, that is not a bug, that is a feature :)

As for "OpConstant is not modified by the relaxed-to-half conversion", it is not clear that that is a bug either. This pass will not necessarily turn a relaxed float32 constant into a half constant. This algorithm starts with all float32 and uses heuristics to decide where to insert converts so the resulting code will execute faster. Even if it decides to insert a convert-to-half on a float32 constant, it is up to the constant folding to fold that into a half constant. So the user will need to call constant folding after this pass.

I would request that the user provide an input SPIR-V file and explain how the resulting SPIR-V is invalid, incorrect, or could be better given the scope of the pass I presented above before re-opening.
