### ISSUE TITLE
opt: dEQP-VK.graphicsfuzz.undefined-integer-in-function

### ISSUE THREAD

**Issue by paulthomson** [KhronosGroup/SPIRV-Tools#3039] opened 2019-11-11 21:45 UTC
This test fails. To reproduce: 

```
spirv-opt -O -o temp.spv *.spv
spirv-val temp.spv
```

[undefined-integer-in-function.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/3833350/undefined-integer-in-function.zip)

**Comment by s-perron** [comment] 2019-11-19 03:02
I cannot reproduce.  @paulthomson Can you double check if this is failing for you?

**Comment by paulthomson** [comment] 2019-11-20 15:57
Oops sorry. You need to do:

```
spirv-opt -O --validate-after-all -o temp.spv *.spv
```

**Comment by s-perron** [comment] 2019-12-02 19:59
This is a duplicate of #3031.

**Closed by s-perron** 2019-12-02 19:59 UTC
