### ISSUE TITLE
spirv-opt fails assertion with "Definition is not registered" message

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#1980] opened 2018-10-17 17:11 UTC
[This archive](https://github.com/KhronosGroup/SPIRV-Tools/files/2488474/files.zip) contains the files necessary to reproduce the issue.

shader.spv was generated from shader.frag using glslang version 7.10.2904.

Running:

spirv-opt --eliminate-dead-branches --merge-return --eliminate-local-multi-store --ccp --eliminate-dead-code-aggressive shader.spv -o temp.spv

leads to this assertion failure:

SPIRV-Tools/source/opt/def_use_manager.cpp:61: void spvtools::opt::analysis::DefUseManager::AnalyzeInstUse(spvtools::opt::Instruction*): Assertion `def && "Definition is not registered."' failed.

Version of spirv-opt used:

SPIRV-Tools v2018.6-dev v2018.5-66-gab45d691 (debug build)

Found using [GraphicsFuzz](https://github.com/google/graphicsfuzz)

**Comment by s-perron** [comment] 2018-10-22 13:14
Duplicate of #1979.  They have the same root problem: loop for a break inside a loop but it manifests in a different way.

**Closed by s-perron** 2018-10-22 13:14 UTC
Labels: bug, component:optimization
