### ISSUE TITLE
spirv-opt segfault when combining options --compact-ids --inline-entry-points-exhaustive

### ISSUE THREAD

**Issue by hevrard** [KhronosGroup/SPIRV-Tools#827] opened 2017-09-20 14:38 UTC
spirv-opt segfaults when invoked with both options --compact-ids --inline-entry-points-exhaustive , e.g.:

`spirv-opt --compact-ids --inline-entry-points-exhaustive shader.spv -o shader_opt.spv`

This seems to be independent of the shader contents, the shader must still be a well-formed spir-v file.

**Comment by dneto0** [comment] 2017-09-20 15:29
I've tried 2 different shaders, and both orderings of optimizations, but haven't reproduced it.

Please provide a reproduction case.

**Comment by hevrard** [comment] 2017-09-20 15:35
Here comes a shader for reproduction, uploaded as a text file to work around github limitations.

[shader.spv.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/1318292/shader.spv.txt)

**Comment by dneto0** [comment] 2017-09-20 19:21
I can reproduce the problem and have seen some bad data internally.  Thanks!

**Comment by dneto0** [comment] 2017-09-20 20:52
The bug is in the compact-ids pass.
On this line it directly modifies the underlying word storing the result id.
https://github.com/KhronosGroup/SPIRV-Tools/blob/master/source/opt/compact_ids_pass.cpp#L35

But the Instruction instance caches the  result id and type id in members result_id_ and type_id_, respectively.

This just proves again that caching is one of the hardest things in computing.  Ugh.

**Comment by dneto0** [comment] 2017-09-20 20:57
Assigned to @atgoo 

The interesting thing is the design of the solution is not obvious.

Do we maximize safety by hiding the `words` member of an ir::Operand and force the modification to go through an API on the instruction?  I suspect there are many good uses of direct access.   

Or do we fix the problem locally in the compact-ids pass and take the risk that the same mistake might be made elsewhere.  I'd like @atgoo to propose a design direction before posting a PR.  The right answer might only be clear once you try to hide the operand data members and see if you lose much.

**Comment by dneto0** [comment] 2017-09-20 21:06
I made ir::Operand::words private and got 31 unique compilation failures.
* Many uses in instruction.h and instruction.cpp are writes, and it would be ok to add a special method for that, because those methods know that they have to update the cached result_id_ and type_id_.
* Most other uses appear to be reads of the data. That would be satisifed by a const & accessor to the words vector.

I suspect the right solution is to make ir::Operand members private and add appropriate getter and setter.

**Comment by dneto0** [comment] 2017-09-26 22:05
I'm taking this.

**Comment by dneto0** [comment] 2017-09-26 22:07
At least I've made a test:  See https://github.com/dneto0/SPIRV-Tools/tree/fix-827

**Comment by dneto0** [comment] 2017-09-27 12:34
And the fix is up for review.

**Closed** 2017-09-27 22:01 UTC
