### ISSUE TITLE
opt: dEQP-VK.graphicsfuzz.return-before-writing-wrong-color

### ISSUE THREAD

**Issue by paulthomson** [KhronosGroup/SPIRV-Tools#3035] opened 2019-11-11 21:42 UTC
This test fails. To reproduce: 

```
spirv-opt -O -o temp.spv *.spv
spirv-val temp.spv
```

[return-before-writing-wrong-color.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/3833331/return-before-writing-wrong-color.zip)

**Comment by s-perron** [comment] 2019-11-19 02:29
Duplicate of #3030.

**Closed by s-perron** 2019-11-19 02:29 UTC
