### ISSUE TITLE
spirv-opt produces code which spirv-val considers invalid (OpPhi on OpTypeImage)

### ISSUE THREAD

**Issue by khyperia** [KhronosGroup/SPIRV-Tools#4066] opened 2020-12-10 15:41 UTC
Reproduction steps are below.

So, the problem is that spirv-val says that using `OpPhi` with a result_type of `OpTypeImage` is invalid. I'm unable to find if this is actually illegal in the spec or not, I can't find any mention of it being illegal, but it's likely I missed something.

Normally, GLSL disallows this by never allowing `texture2D` in an `x ? y : z` expression, not allowing local variables of type `texture2D`, and the like. Unoptimized, I believe this validation error will never be hit. However, once `spirv-opt` enters the picture, things change.

Because `spirv-opt` can inline functions, it inlines the `selectTexture` function below. Then, various other optimizations run, and the if statement boils down to an `OpPhi` selecting either `tex1` or `tex2` based on which branch was taken in the if statement. This then fails `spirv-val`, which disallows `OpTypeImage` in `OpPhi`.

I don't know if the true error is `spirv-opt` generating incorrect code, or `spirv-val` incorrectly disallowing `OpTypeImage` in `OpPhi`. People better than I am at reading the SPIR-V spec should answer that :P

Thanks so much for your time!

(The fact that `spirv-val` disallows `OpTypeImage` in `OpPhi` was originally discovered https://github.com/EmbarkStudios/rust-gpu/issues/330 and so I investigated if this could happen elsewhere in the ecosystem and how other tools handle this scenario. So, I figured I'd report my findings.)

---

Shader playground example showing the repro: http://shader-playground.timjones.io/68dbf3cf07452fdd775b34d70e54f87e

GLSL code:

```glsl
#version 420

in vec2 inUV;
in float texSelector;
layout (binding = 0) uniform texture2D tex1;
layout (binding = 1) uniform texture2D tex2;
layout (binding = 2) uniform sampler samp;
out vec4 result;

texture2D selectTexture(texture2D one, texture2D two) {
    if (texSelector == 0) {
    	return one;
    } else {
    	return two;
    }
}

void main()
{
    result = texture(sampler2D(selectTexture(tex1, tex2), samp), inUV);
}
```

Compiled with glslang (pre-optimization, passes spirv-val):

<details>
  <summary>Click to expand</summary>

  ```spirv
; SPIR-V
; Version: 1.0
; Generator: Khronos Glslang Reference Front End; 8
; Bound: 45
; Schema: 0
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Fragment %main "main" %texSelector %result %inUV
               OpExecutionMode %main OriginUpperLeft
               OpSource GLSL 420
               OpName %main "main"
               OpName %selectTexture_t21_t21_ "selectTexture(t21;t21;"
               OpName %one "one"
               OpName %two "two"
               OpName %texSelector "texSelector"
               OpName %result "result"
               OpName %tex1 "tex1"
               OpName %tex2 "tex2"
               OpName %samp "samp"
               OpName %inUV "inUV"
               OpDecorate %texSelector Location 1
               OpDecorate %result Location 0
               OpDecorate %tex1 DescriptorSet 0
               OpDecorate %tex1 Binding 0
               OpDecorate %tex2 DescriptorSet 0
               OpDecorate %tex2 Binding 1
               OpDecorate %samp DescriptorSet 0
               OpDecorate %samp Binding 2
               OpDecorate %inUV Location 0
       %void = OpTypeVoid
          %3 = OpTypeFunction %void
      %float = OpTypeFloat 32
          %7 = OpTypeImage %float 2D 0 0 0 1 Unknown
%_ptr_UniformConstant_7 = OpTypePointer UniformConstant %7
          %9 = OpTypeFunction %7 %_ptr_UniformConstant_7 %_ptr_UniformConstant_7
%_ptr_Input_float = OpTypePointer Input %float
%texSelector = OpVariable %_ptr_Input_float Input
    %float_0 = OpConstant %float 0
       %bool = OpTypeBool
    %v4float = OpTypeVector %float 4
%_ptr_Output_v4float = OpTypePointer Output %v4float
     %result = OpVariable %_ptr_Output_v4float Output
       %tex1 = OpVariable %_ptr_UniformConstant_7 UniformConstant
       %tex2 = OpVariable %_ptr_UniformConstant_7 UniformConstant
         %34 = OpTypeSampler
%_ptr_UniformConstant_34 = OpTypePointer UniformConstant %34
       %samp = OpVariable %_ptr_UniformConstant_34 UniformConstant
         %38 = OpTypeSampledImage %7
    %v2float = OpTypeVector %float 2
%_ptr_Input_v2float = OpTypePointer Input %v2float
       %inUV = OpVariable %_ptr_Input_v2float Input
       %main = OpFunction %void None %3
          %5 = OpLabel
         %33 = OpFunctionCall %7 %selectTexture_t21_t21_ %tex1 %tex2
         %37 = OpLoad %34 %samp
         %39 = OpSampledImage %38 %33 %37
         %43 = OpLoad %v2float %inUV
         %44 = OpImageSampleImplicitLod %v4float %39 %43
               OpStore %result %44
               OpReturn
               OpFunctionEnd
%selectTexture_t21_t21_ = OpFunction %7 None %9
        %one = OpFunctionParameter %_ptr_UniformConstant_7
        %two = OpFunctionParameter %_ptr_UniformConstant_7
         %13 = OpLabel
         %16 = OpLoad %float %texSelector
         %19 = OpFOrdEqual %bool %16 %float_0
               OpSelectionMerge %21 None
               OpBranchConditional %19 %20 %24
         %20 = OpLabel
         %22 = OpLoad %7 %one
               OpReturnValue %22
         %24 = OpLabel
         %25 = OpLoad %7 %two
               OpReturnValue %25
         %21 = OpLabel
               OpUnreachable
               OpFunctionEnd
```
</details>

Optimized SPIR-V that fails spirv-val:

<details>
  <summary>Click to expand</summary>

  ```spirv
; SPIR-V
; Version: 1.0
; Generator: Khronos Glslang Reference Front End; 8
; Bound: 66
; Schema: 0
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Fragment %main "main" %texSelector %result %inUV
               OpExecutionMode %main OriginUpperLeft
               OpSource GLSL 420
               OpName %main "main"
               OpName %texSelector "texSelector"
               OpName %result "result"
               OpName %tex1 "tex1"
               OpName %tex2 "tex2"
               OpName %samp "samp"
               OpName %inUV "inUV"
               OpDecorate %texSelector Location 1
               OpDecorate %result Location 0
               OpDecorate %tex1 DescriptorSet 0
               OpDecorate %tex1 Binding 0
               OpDecorate %tex2 DescriptorSet 0
               OpDecorate %tex2 Binding 1
               OpDecorate %samp DescriptorSet 0
               OpDecorate %samp Binding 2
               OpDecorate %inUV Location 0
       %void = OpTypeVoid
          %3 = OpTypeFunction %void
      %float = OpTypeFloat 32
          %7 = OpTypeImage %float 2D 0 0 0 1 Unknown
%_ptr_UniformConstant_7 = OpTypePointer UniformConstant %7
%_ptr_Input_float = OpTypePointer Input %float
%texSelector = OpVariable %_ptr_Input_float Input
    %float_0 = OpConstant %float 0
       %bool = OpTypeBool
    %v4float = OpTypeVector %float 4
%_ptr_Output_v4float = OpTypePointer Output %v4float
     %result = OpVariable %_ptr_Output_v4float Output
       %tex1 = OpVariable %_ptr_UniformConstant_7 UniformConstant
       %tex2 = OpVariable %_ptr_UniformConstant_7 UniformConstant
         %34 = OpTypeSampler
%_ptr_UniformConstant_34 = OpTypePointer UniformConstant %34
       %samp = OpVariable %_ptr_UniformConstant_34 UniformConstant
         %38 = OpTypeSampledImage %7
    %v2float = OpTypeVector %float 2
%_ptr_Input_v2float = OpTypePointer Input %v2float
       %inUV = OpVariable %_ptr_Input_v2float Input
       %main = OpFunction %void None %3
          %5 = OpLabel
         %56 = OpLoad %float %texSelector
         %57 = OpFOrdEqual %bool %56 %float_0
               OpSelectionMerge %58 None
               OpBranchConditional %57 %59 %60
         %59 = OpLabel
         %61 = OpLoad %7 %tex1
               OpBranch %58
         %60 = OpLabel
         %62 = OpLoad %7 %tex2
               OpBranch %58
         %58 = OpLabel
         %65 = OpPhi %7 %61 %59 %62 %60
         %37 = OpLoad %34 %samp
         %39 = OpSampledImage %38 %65 %37
         %43 = OpLoad %v2float %inUV
         %44 = OpImageSampleImplicitLod %v4float %39 %43
               OpStore %result %44
               OpReturn
               OpFunctionEnd
```
</details>

spirv-val error message on the optimized module:

```
error: line 57: Result type cannot be OpTypeImage
  %32 = OpPhi %12 %30 %28 %31 %29
```

**Comment by dneto0** [comment] 2020-12-10 16:46
Thanks for the great bug report.  It's really clear and has a tiny reproducer. (Also, I hadn't seen the details trick but it's really useful)

I guess the first thing is I'm surprised you can return a texture (or sampler or sampled texture) from a function.    That's where I'd look first.  

I know HLSL code does all sorts of interesting things with passing texture handles around, but when compiling to Vulkan SPIR-V all those usages have to be boiled away.  We crafted a heuristic recipe to do that in the cases we've seen.  https://github.com/microsoft/DirectXShaderCompiler/blob/master/docs/SPIRV-Cookbook.rst  

My gut feel is that returning a texture (or sampler or sampled texture) from a function looks like a loophole we've overlooked. 

The rule that has kicked in is this one in 2.16.1 Universal validation rules:

> If instructions dereference a composite to get an image or a sampler, behavior is undefined unless all the dereferencing Indexes are dynamically-uniform. Such instructions must be in the same block in which their Result &lt;id&gt; are consumed. Such Result &lt;id&gt; must not appear as operands to OpPhi instructions or OpSelect instructions, or any instructions other than the image instructions specified to operate on them.

**Comment by dneto0** [comment] 2020-12-10 16:55
Ah, the description of OpTypeFunction says:

> _Return Type_ is the type of the return value of functions of this type. It must be a [concrete](https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#Concrete) or [abstract](https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#Abstract) type, or a pointer to such a type. If the function has no return value, Return Type must be OpTypeVoid.

Concrete type is:  A numerical scalar, vector, or matrix type, or physical pointer type, or any aggregate containing only these types.

Abstract type is: An OpTypeVoid or OpTypeBool, or logical pointer type, or any aggregate type containing any of these.

(and aggregates are structures or arrays)

So it's invalid to declare a function that returns an image or a sampler or a sampled image.

That's a missing validation rule in the SPIR-V validator.  :-(

**Comment by s-perron** [comment] 2020-12-10 17:01
My understanding was that code like this was not legal in Vulkan.  The choice between the textures cannot be done.  For HLSL code that does this, we do "Legalization" to try to optimize the selection away, and generate legal code.  In this case, the choice cannot be determined at compile time, so we are left with the OpPhi.

I just noticed that David mentioned the specific rule broken in this case: You cannot return an opaque type.  You also should not be able to have a store of an opaque type.

@dneto0 If we add the validation rule that mentioned, it should be guarded by the "legalize-hlsl" flags.

**Comment by khyperia** [comment] 2020-12-10 17:01
Ah awesome! Looks like this is very tied in together with https://github.com/KhronosGroup/glslang/issues/2382, pretty much the same issue (that one is on the language side).

**Comment by dneto0** [comment] 2020-12-10 17:01
I looked at the GLSL 4.5 spec.  I don't see a restriction like this on the return type of a function.   So that would be a gap of something that GLSL apparently(?) allows but SPIR-V does not.

The Vulkan flavour of GLSL (defined [here](https://github.com/KhronosGroup/GLSL/blob/master/extensions/khr/GL_KHR_vulkan_glsl.txt)) adds the ability to create combined image-samplers via constructor syntax:

```
     Constructors can then be used to combine a sampler and a texture at the
    point of making a texture lookup call:

        texture(sampler2D(t, s), ...);
```
And issue 9 in that spec discusses where those constructors can be used.   It was resolved that they can only be used at point-of-use.  So it's syntactic sugar for a specific thing that isn't really a "function".  (Or at least it could be argued that way.)

**Comment by dneto0** [comment] 2020-12-10 17:03
> Ah awesome! Looks like this is very tied in together with KhronosGroup/glslang#2382, pretty much the same issue (that one is on the language side).

Yes. And thanks for finding that reference.

**Comment by dneto0** [comment] 2020-12-10 17:04
I'll close this in favour of the new issue #4068 to enhance validation.

**Closed by dneto0** 2020-12-10 17:04 UTC

**Comment by khyperia** [comment] 2020-12-10 17:09
Should there be a spec issue filed to make `OpPhi` on `OpTypeImage` explicitly illegal? In other shader languages (_cough_ `rust-gpu`), it's currently valid to select between images without resorting to a separate function and `return` trickery, and as far as I can tell, there's nothing in the SPIR-V spec that disallows that (it's only disallowed by GLSL). Obviously `rust-gpu` needs to disallow this, but it'd be nice to base that restriction on actual SPIR-V spec wording.
