### ISSUE TITLE
Spirv-link Adding layout(local_size_x = 1, local_size_y = 1) in; to unused compute shader results in black framebuffer.

### ISSUE THREAD

**Issue by Rainer-1** [KhronosGroup/SPIRV-Tools#4152] opened 2021-03-01 18:51 UTC
Adding `layout(local_size_x = 1, local_size_y = 1) in;` to a compute shader that isn't even used in a program, leads to a black screen (whereas not specifying the layout in the compute shader leads the vertex, geometry, and fragment shaders to output what is expected onto the screen). This error has been present since the previous version of the LunarG SDK, so this is not due to the SDK version that was just released.

**Comment by pierremoreau** [comment] 2021-03-01 21:23
What leads you to believe this is an issue with spirv-link? Which driver and OS are you experiencing those issues on?

**Comment by Rainer-1** [comment] 2021-03-02 20:39
@pierrmoreau I am experiencing this issue on Debian testing on Mesa 20.3.4-1 for Intel HD Graphics 630.

**Comment by pierremoreau** [comment] 2021-03-02 21:02
Could you please share the before and after SPIR-V modules? About 36 bytes out of the 72 bytes will come from the linker adding
```
OpModuleProcessed "Linked by SPIR-V Tools Linker"
```
to the module, which is purely informative and has no impact.

Also, `layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;` being the default does not matter here: the linker will not remove information from the shader even if it turns out to match what the default is, and will instead just leave it in.

**Comment by Rainer-1** [comment] 2021-03-02 21:44
@pierremoreau I had forgotten to mention that I was using spirv-opt after spirv-link (but the error occurs regardless of whether or not spirv-link is used). Not using spirv-opt still results in an increase in size of 72 bytes. Here are the files: 
[shadersSpirv.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/6071986/shadersSpirv.zip)

**Comment by pierremoreau** [comment] 2021-03-02 22:06
Thank you for providing the shaders.

Could you please explain how both files were generated? As far as I can see, both include the `LocalSize` on the compute shader and both were linked using spirv-link, but the implementation of function `a` and function `d` are slightly different.

**Comment by Rainer-1** [comment] 2021-03-02 22:47
@pierremoreau Each shader was compiled with:
`glslangValidator -Od -e a --source-entrypoint main --target-env vulkan1.2 -V InputFileName -o SpvFileName`

and then linked with:
`spirv-link --target-env vulkan1.2 VertexShaderSpvName GeometryShaderSpvName FragmentShaderSpvName ComputeShaderSpvName -o LinkedShadersName`

"LinkedShadersName" is what the "shaders_working" and "shaders_not_working" were in the shadersSpirv.zip file above.

**Comment by pierremoreau** [comment] 2021-03-03 21:48
Thank you for those instructions, so if I understood correctly we have the following:

```
a_working.spv <- compile(a_working.vert)
b_working.spv <- compile(b_working.geo)
c_working.spv <- compile(c_working.frag)
d_working.spv <- compile(d_working.comp)
working.spv <- link(a_working.spv, b_working.spv, c_working.spv, d_working.spv)

a_failing.spv <- compile(a_failing.vert)
b_failing.spv <- compile(b_failing.geo)
c_failing.spv <- compile(c_failing.frag)
d_failing.spv <- compile(d_working.comp)
failing.spv <- link(a_failing.spv, b_failing.spv, c_failing.spv, d_failing.spv)

where
a_working.vert is identical to a_failing.vert
b_working.geo is identical to b_failing.geo
c_working.frag is identical to c_failing.frag
d_working.comp is d_failing.comp minus "layout(local_size_x = 1, local_size_y = 1) in;"
```

which leaves me wondering why `a_working.spv` and `a_failing.spv` are different (based on the shaders you shared; spirv-link is basically doing a copy/paste of the content of each module and tweaking variable/function IDs, but it should never change the implementation of a function).

Are you able to share the intermediate SPIR-V modules (i.e. before they all get linked into a single module) as well as the original GLSL code? And if not, could you please make sure that `a_working.spv` and `a_failing.spv` are indeed identical? (Though if they are identical, I will most likely need the intermediate modules to try to reproduce and understand why the linker would make any changes to the body of functions.)

**Comment by Rainer-1** [comment] 2021-03-03 23:33
@pierremoreau Yes, the flow chart you posted represents how the compilation was done.

Here are the spv modules:
Working:
[shadersWorking.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/6079818/shadersWorking.zip)
Not Working:
[shadersNotWorking.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/6079821/shadersNotWorking.zip)

Here is the source:
[shaderSrc.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/6079823/shaderSrc.zip)

**Comment by pierremoreau** [comment] 2021-03-03 23:47
Thank you for all the files! I will have a look at those tomorrow.

**Comment by pierremoreau** [comment] 2021-03-04 19:09
There is a difference when compiling shader1.comp with or without `layout(local_size_x = 1, local_size_y = 1) in;`: in both cases the local size execution mode of `d` is set to (1, 1, 1), but if the layout is specified the compiler also defines a `%gl_WorkGroupSize` variable set to the specified value, which is not the case if the layout was not specified (which explains the 72 bytes difference between the working and not working merged binaries, as you can already see that difference between shader.comp.spv from shadersWorking.zip and shader.comp.spv from shadersNotWorking.zip).

I will try to feed the merged binary to Mesa’s spirv_to_nir and see what happens.

If it is not too difficult, could you try loading your shaders in your app from the individual SPIR-V modules rather than from the linked one, and see if you get different behaviours from using the shaders from shadersWorking.zip or from shadersNotWorking.zip.

**Comment by Rainer-1** [comment] 2021-03-04 19:57
@pierremoreau Linking the vertex, geometry, and fragment shaders together, but keeping the compute shader separate (spirv-link not invoked with the compute shader spv as input) makes the program work as expected (tested with various layout(local_size_x=...)).

**Comment by pierremoreau** [comment] 2021-03-04 20:33
Ah, thank you for testing that! That wasn’t the configuration I was thinking of, but the result is the same. :slightly_smiling_face: 

> The compute shader spv still increases by 72 bytes, like before.

Not too surprising, given that it is _glslangValidator_ being the cause for those extra 72 bytes, not _spirv-link_.

**Comment by pierremoreau** [comment] 2021-03-04 20:49
I think I found something: could you please try the same thing that you just tried, but have the vertex, fragment, and compute shaders together in one linked SPIR-V module, and have geometry in its own module?

Running spirv2nir on the not-working and working linked modules, for each of the entry points, gave no difference for either the vertex, fragment, or compute shaders, but for the geometry shader I got the following differences:

```
Failing:
vertices out: 1
input primitive: LINES
output primitive: LINES

Working:
vertices out: 4
input primitive: POINTS
output primitive: TRIANGLE_STRIP
```

Both the working.spv and notWorking.spv have the following
```
               OpExecutionMode %b InputPoints
               OpExecutionMode %b Invocations 1
               OpExecutionMode %b OutputTriangleStrip
               OpExecutionMode %b OutputVertices 4
```

I’ll continue debugging this.

**Comment by Rainer-1** [comment] 2021-03-04 21:39
@pierremoreau 
When compiling the geometry shader separately, and all other shaders together, everything works as expected. However, using spirv-opt after the link leads to ```
error: line 121: Cannot form constants of 8- or 16-bit types
  %short_200 = OpConstant %short 200
``` being printed.

In addition, 
When linking everything together, I tried layout(local_size_x = 4, local_size_y = 4, local_size_z=4) in; , and the framebuffer was not black, but only one in every two triangles was rendered.

Using layout(local_size_x = 3, local_size_y = 3, local_size_z=3) in; leads to what happens when using  layout(local_size_x = 4, local_size_y = 4, local_size_z=4) in;  in addition to the primitive topology changing to outline.

Using layout(local_size_x = 5, local_size_y = 5, local_size_z=5) in; renders everything as expected (fill primitive toplogy).

**Comment by pierremoreau** [comment] 2021-03-04 21:58
Found the problem, and it is not an issue with the linker.

When you add the explicit `layout(local_size_x = 1, local_size_y = 1) in;`, _glslangValidator_ defines the SPIR-V built-in variable `WorkgroupSize`, which was the reason for the extra 72 bytes that the compute shader takes, which is fine. The problem is that Mesa sees that `WorkgroupSize` built-in and without checking that it is indeed processing a compute shader, saves the value into some internal structures. However, the internal structures about compute, geometry information, etc. are part of a union, so setting some information for compute will override some information in the geometry structure as they share the same memory.

Which is what is happening here; it properly parsed and stored all the information about the output topology type, number of primitives, etc., but when it later sees the `WorkgroupSize`, some of that information gets overwritten by the workgroup size value.

If you are ready to compile your own Mesa, you could try applying the patch from this merge request to fix the issue: https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/9418.

**Comment by Rainer-1** [comment] 2021-03-05 19:41
@pierremoreau Since it seems like Mesa 21.0 is going to release very soon, I'll just wait for the update. Thank you for fixing the issue.

**Comment by Rainer-1** [comment] 2021-03-05 21:23
@pierremoreau I encountered some difficulties building mesa, and it seems like mesa 21.0 is going to release soon, so I'll just wait until it releases. Thank you for fixing the issue.

**Comment by pierremoreau** [comment] 2021-03-05 21:43
The fix hasn’t been merged yet and I am not sure it will make it into 21.0, but it should probably make it into one of the following point releases.

This issue can be closed as it turned out to not be related to spirv-link. Feel free to follow the progress on the Mesa MR, and if you still experience some issues even with the patched version, feel free to reopen this one.

**Closed** 2021-03-05 23:06 UTC
