### ISSUE TITLE
spirv-fuzz: TransformationOutlineFunction produces invalid binary when unreachable blocks reference outlined blocks

### ISSUE THREAD

**Issue by Vasniktel** [KhronosGroup/SPIRV-Tools#4298] opened 2021-05-25 13:34 UTC
This can be reproduced on 91931ffcd22ae774ed932c98c2d0319db9720d93 with
> spirv-fuzz --replay=transformations.binary original.spv --replay-validation -o replayed.spv

The reason is that some unreachable block references one of the blocks in the outlined region. The instruction in that unreachable block is not updated which causes the following error
> ERROR 0:0:133: Block(s) {36[%36]} are referenced but not defined in function 4[%main]
  %main = OpFunction %void DontInline %3

[data.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/6539663/data.zip)

**Comment by afd** [comment] 2021-05-27 22:47
I could not reproduce this on the latest commit using the provided files, but as it was clear what the problem was I have pushed a fix in #4308.

**Closed** 2021-06-01 10:44 UTC
