### ISSUE TITLE
spirv-opt problems

### ISSUE THREAD

**Issue by mihaly-sisak** [KhronosGroup/SPIRV-Tools#5596] opened 2024-02-28 13:14 UTC
I try to ship optimized OpenGL code in my game EvoLife. Without this steps the shader compilation takes longer on first launch. My optimizing pipeline:
```
glslang --quiet -G -S <stage> -o <filename>.spv <filename>.glsl
spirv-opt -Oconfig=glsl_opt_config.cfg -o <filename>_opt.spv <filename>.spv
spirv-cross --version 430 --no-es --output <filename>_opt.<stage>.glsl <filename>_opt.spv
```
My problem is that I can not run spirv-opt with -O, I have to use -Oconfig with the file attached. My starting point was the -O list and I bisected which options cause issues.
[glsl_opt_config.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/14434380/glsl_opt_config.txt)
Line 3 --merge-return: causes glsl shaders to behave differently than unoptimized versions
Line 4 --inline-entry-points-exhaustive: can not run without merge-return
Line 40 and 43 --merge-blocks: causes spirv-cross to abort on some shaders

Please let me know how can I help to resolve this problem. In the meantime maybe others will find this and can use the same workaround.

**Comment by cassiebeckley** [comment] 2024-02-28 17:47
Thank you for reporting this issue. Would you be able to post an example of a shader that behaves differently with `--merge-return`?

**Comment by mihaly-sisak** [comment] 2024-02-29 11:45
The input file is a 11 kLOC file that contains almost all of my glsl source code. Is it possible to provide an example without it being public?

**Comment by mihaly-sisak** [comment] 2024-02-29 12:14
Looking into the issue more deeply and quickly learning about how to disassemble and read binary spriv files for me it looks like the issue will be in spirv-cross. Will raise an issue there.

**Comment by cassiebeckley** [comment] 2024-02-29 19:11
It would be better if you were able to provide a minimal reproducible example of a SPIR-V shader which has this issue. You might be able to create one semi-automatically using [`spirv-reduce`](https://github.com/KhronosGroup/SPIRV-Tools/?tab=readme-ov-file#reducer) on `<filename>.spv`. In the "interestingness function", you'd want to run `glslang -O` and test for whether the behavior has changed.

It may also help if you can describe how the change in the behavior of glsl shaders after running the `merge-return` pass.

**Comment by s-perron** [comment] 2024-05-29 13:06
We will close this issue because there is nothing we can do with the current information. Please open a new issue when with more information on how to reproduce it.

> The input file is a 11 kLOC file that contains almost all of my glsl source code. Is it possible to provide an example without it being public?

I'm not sure how our legal team would feel about it.

**Closed by s-perron** 2024-05-29 13:06 UTC
Labels: component:optimization
