### ISSUE TITLE
opt: invalid SPIR-V produced: OpPhi's number of incoming blocks (3) does not match block's predecessor count (4).

### ISSUE THREAD

**Issue by paulthomson** [KhronosGroup/SPIRV-Tools#2712] opened 2019-07-03 15:26 UTC
[bug_report.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/3355664/bug_report.zip)

Issue found using [GraphicsFuzz](https://github.com/google/graphicsfuzz).

Tool versions:

* glslangValidator commit hash: 40c16ec0b3ad03fc170f1369a58e7bbe662d82cd
* spirv-opt commit hash: 4a00a80c40484a6f6f72f48c9d34943cf8f180d4

To reproduce:

`glslangValidator -V shader.comp -o shader.comp.spv`

`spirv-opt shader.comp.spv -o temp.spv --validate-after-all --private-to-local --eliminate-local-multi-store --simplify-instructions --eliminate-dead-inserts --eliminate-dead-branches --merge-return`

The following shader files are included in the attached archive, some of which are also shown inline below:

* 0_glsl/shader.comp
* 1_spirv/shader.comp.spv
* 1_spirv_asm/shader.comp.asm

0_glsl/shader.comp:

```
#version 310 es


precision highp float;

layout(std430, binding = 0) buffer doesNotMatter {
 vec4 _compute_data[];
} ;
layout(local_size_x = 1, local_size_y = 1, local_size_z = 10) in;
float nb_mod()
{
 float s;
 s = 0.0;
 for(
     int i = 1;
     i < 800;
     1
 )
  {
   int GLF_live1_looplimiter2;
   for(
       int GLF_live1i = 0;
       true;
       1
   )
    {
     if(GLF_live1_looplimiter2 >= 5)
      {
       break;
       return 1.0;
      }
     return 1.0;
    }
   if(float(i) <= 0.01)
    {
     break;
    }
   return 1.0;
  }
 return s;
}
void main()
{
 nb_mod();
}

```

**Comment by s-perron** [comment] 2019-07-11 23:17
Duplicate of #2702.

**Closed by s-perron** 2019-07-11 23:17 UTC
