### ISSUE TITLE
opt: dEQP-VK.graphicsfuzz.discard-in-loop

### ISSUE THREAD

**Issue by paulthomson** [KhronosGroup/SPIRV-Tools#3033] opened 2019-11-11 21:40 UTC
This test fails. To reproduce: 

```
spirv-opt -O -o temp.spv *.spv
spirv-val temp.spv
```

[discard-in-loop.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/3833323/discard-in-loop.zip)

**Comment by s-perron** [comment] 2019-11-19 02:26
Duplicate of #3031.

**Closed by s-perron** 2019-11-19 02:26 UTC
