### ISSUE TITLE
opt: dEQP-VK.graphicsfuzz.unreachable-discard-statement

### ISSUE THREAD

**Issue by paulthomson** [KhronosGroup/SPIRV-Tools#3042] opened 2019-11-11 21:47 UTC
This test fails. To reproduce: 

```
spirv-opt -O -o temp.spv *.spv
spirv-val temp.spv
```

[unreachable-discard-statement.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/3833353/unreachable-discard-statement.zip)

**Comment by s-perron** [comment] 2019-11-19 03:07
Duplicate of #3038

**Closed by s-perron** 2019-11-19 03:07 UTC
