### ISSUE TITLE
linking vs specialization constants

### ISSUE THREAD

**Issue by airlied** [KhronosGroup/SPIRV-Tools#4585] opened 2021-10-19 21:30 UTC
This is likely more of a spec question, but maybe the linker devs have some ideas.

Now since I don't see a way to expose spec consts in CL C, and GLSL has them as user defined, this is probably not something that has been considered.

If I have two execution units with defined spec constants and link them, what happens if the SpecId are the same in both units.

What happens if they are the same id with same types,
What happens if they are the same id with different types?

**Comment by pierremoreau** [comment] 2021-10-29 18:34
Thank you for the ping.

This is not something I had considered.
In a way, the linker is more of a SPIR-V merger that also resolves import/export symbols. It does not look at anything else, like checking that the input of a fragment shader matches the output of the vertex shader passed in, for example.

What the spirv-linker will do at the moment, is keep both SpecConstant ops and their decoration with the initial SpecId, so there will be two different variables under the same SpecId. From having a quick look at the spec, that does not seem to be invalid but would definitely be quite confusing to consumers (and I believe I ran into that precise issue this morning).

It‘s hard to say what should happen.
```glsl
// Vertex shader
// …
layout (constant_id = 0) const bool earlyBreak;
// …

// Fragment shader
// …
layout (constant_id = 0) const bool earlyBraek;
// …
```
Same ID, same type, and same name if it wasn‘t for the typo. Could probably be merged.

```glsl
// Vertex shader
// …
layout (constant_id = 0) const bool earlyBreak;
// …

// Fragment shader
// …
layout (constant_id = 0) const bool lateBreak;
// …
```
Same ID, same type, but should not be merged (from the point of view of the user).

If the types do not even match, spirv-linker should bail out.

For Vulkan, the specialization takes place when defining a pipeline stage, so it could look up which specialization constants are used by just that entry point (except specialization constants are not listed as part of the entry point interface, so it would not be able to) and then there would be no issue.
For OpenCL, this takes place on the program object so there is no way of knowing which of the two SpecId 0 it should apply (even if the specialization constants were listed as part of the entry point interface, since we do not know yet which entry point will be selected).

It does not feel like SPIR-V was designed with having in mind that the user would combine together different modules before giving them to the implementation. Nor did I do a good job at making sure the linker would generate valid SPIR-V.

**Closed** 2023-06-16 13:46 UTC
