### ISSUE TITLE
spirv-val does not validate Flat decoration requirement for builtins

### ISSUE THREAD

**Issue by HansKristian-Work** [KhronosGroup/SPIRV-Tools#3154] opened 2020-01-27 13:16 UTC
This SPIR-V passes validation, even if Flat is removed from Layer Builtin input in fragment shader:
```
; SPIR-V
; Version: 1.0
; Generator: Khronos Glslang Reference Front End; 8
; Bound: 12
; Schema: 0
               OpCapability Shader
               OpCapability Geometry
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Fragment %main "main" %layer %gl_Layer
               OpExecutionMode %main OriginUpperLeft
               OpSource GLSL 450
               OpName %main "main"
               OpName %layer "layer"
               OpName %gl_Layer "gl_Layer"
               OpDecorate %layer Location 0
               ;OpDecorate %gl_Layer Flat
               OpDecorate %gl_Layer BuiltIn Layer
       %void = OpTypeVoid
          %3 = OpTypeFunction %void
        %int = OpTypeInt 32 1
%_ptr_Output_int = OpTypePointer Output %int
      %layer = OpVariable %_ptr_Output_int Output
%_ptr_Input_int = OpTypePointer Input %int
   %gl_Layer = OpVariable %_ptr_Input_int Input
       %main = OpFunction %void None %3
          %5 = OpLabel
         %11 = OpLoad %int %gl_Layer
               OpStore %layer %11
               OpReturn
               OpFunctionEnd
```

**Comment by alan-baker** [comment] 2020-01-27 14:08
Can you point to this language in the spec? I don't see this requirement in either SPIR-V or Vulkan.

**Comment by HansKristian-Work** [comment] 2020-01-27 14:19
Vulkan spec, 8.11: "Fragment shader inputs that are signed or unsigned integers, integer vectors, or any double-
precision floating-point type must be decorated with Flat."

**Comment by sfricke-samsung** [comment] 2021-02-02 06:39
Internal Vulkan MR 4368 to add to spec as well

**Comment by sfricke-samsung** [comment] 2021-02-02 06:42
Also realize this is a duplicate of #3066

**Closed** 2022-07-07 17:03 UTC
Labels: enhancement
