### ISSUE TITLE
opt: dEQP-VK.graphicsfuzz.return-float-from-while-loop

### ISSUE THREAD

**Issue by paulthomson** [KhronosGroup/SPIRV-Tools#3036] opened 2019-11-11 21:43 UTC
This test fails. To reproduce: 

```
spirv-opt -O -o temp.spv *.spv
spirv-val temp.spv
```

[return-float-from-while-loop.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/3833334/return-float-from-while-loop.zip)

**Comment by s-perron** [comment] 2019-11-19 02:31
Duplicate of #3031.

**Closed by s-perron** 2019-11-19 02:31 UTC
