### ISSUE TITLE
Add pretty-printing (disassembling) for instructions, basic blocks and operands.

### ISSUE THREAD

**Issue by dnovillo** [KhronosGroup/SPIRV-Tools#988] opened 2017-11-21 18:14 UTC

**Comment by dneto0** [comment] 2017-11-23 23:32
@alan-baker discovered some code in the test tree that disassembles a single instruction. But it fails on a single OpConstant instruction, likely because there is no definition of the type id.

The right way to do partial-disassembly is to specialize the full-module disassembler so you still run through the entire module but only pay attention to some of the strings coming out for the instructions you're interested in.

**Comment by dneto0** [comment] 2017-12-19 15:27
Some more on this:  Yes, you need the information from earlier in the module, especially for type information.   So you need to send in the entire module, and then watch for the particular instruction that you want to disassemble.  You could specify that as a word offset from the start of the module, but you probably don't have that offset information handy.   

Instead, you could look for the sequence of binary words that make up the instruction, and look for a match that is instruction-aligned. I think it's true that two instructions with exactly the same sequence of words should always map to the same disassembly string.  So it doesn't matter if there are two copies of something like OpBranchConditional %c %truebranch %falsebranch because they should disassemble to the string. (Note that instructions that return a result id are always unique'd since IDs live in a global number space.)

The other thing that helps get to a solution is that spvtools::ir::Instruction now holds onto its IRContext, and so can find its containing module.  So it has full information to reproduce its own disassembly.

**Comment by alan-baker** [comment] 2018-01-12 16:25
Rebased, squashed and committed as 672494da13d54cf72d41edc67ecc6b53c561afc6.

**Closed by alan-baker** 2018-01-12 16:25 UTC
Labels: component:general-utility, enhancement
