### ISSUE TITLE
Optimizator fails with large IDs

### ISSUE THREAD

**Issue by archimedus** [KhronosGroup/SPIRV-Tools#2425] opened 2019-03-04 09:39 UTC
The `Optimizer` fails optimizing code from the attachment
[lots_ids.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/2925700/lots_ids.txt)

The issue started to appear when code IDs that does not fit into 16-bit fields are being used.

**Comment by archimedus** [comment] 2019-03-04 09:45
Mentioned above file is a disassembly of binary produced by optimizer.
Also seems in the header it hints failing stage:

```
; IR before pass inline-entry-points-exhaustive
; SPIR-V
; Version: 1.0
; Generator: Khronos SPIR-V Tools Assembler; 0
; Bound: 4194001
; Schema: 0
```

**Comment by s-perron** [comment] 2019-03-04 15:52
Yes, this is expected behaviour.  In the spir-v spec, there is a limit in the maximum value for the id bound: 0x3FFFFF.  See https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#_a_id_limits_a_universal_limits.

During optimization spirv-opt needs to create new ids.  If during optimization, it goes over the limit, optimization will have to stop because it will not necessarily be able to create a legal spir-v binary.

There are two solutions to this problem.  The easiest is to use the `--max-id-bound=<n>` options to raise the max id bound.  However, it is the your responsibility to make sure that all of the ICDs you will run on will accept spir-v files with the higher id bound.

You can also change the optimizations that are run and insert compact ids somewhere.  This might lower the id bound enough.

You can also do a combination of these.  Hope that helps.

**Comment by archimedus** [comment] 2019-03-04 16:06
Due to code follows mentioned above rules (IDs less than 0x3FFFFF) I suppose the code is valid.

I know nothing about optimizer and cannot predict how many IDs it requires for optimization.

I suppose optimizer need to be fixed.

**Comment by alegal-arm** [comment] 2019-03-04 16:40
I believe that the problematic SPIR-V code doesn't actually contain 0x3FFFFF ids. It contains a bit more than 10K opcodes and one of them has 0x3FFFFF as the id. There should be plenty of room for the optimizer to create new IDs

**Comment by s-perron** [comment] 2019-03-04 16:42
It depends on what opportunities it finds.  In your example, the large function gets inlined.  That means a new id is needed for every id defined in that function.  You almost have to double the number of ids just for inlining.  However, if inlining is turned off or most of the ids are defined in the entrypoint, then fewer ids will be needed.

In general, it is hard to predict how many ids the optimizer will needed, and how many will still be in use after all of the optimizations are done.

I don't think it is possible to "fix" the compiler in this case.  Because users can run the pass in any order, or even just run a single pass, each pass must output a valid spir-v binary.  In this case, is impossible for inlining to do inlining and produce a valid spir-v binary.  Because some passes are not just requested (see https://github.com/Microsoft/DirectXShaderCompiler/blob/master/docs/SPIRV-Cookbook.rst), but they are required, we cannot skip optimizations that cannot be done.

We have made a conscious decision to fail when we hit this type of error.  As I mentioned above there are a couple ways for you to work around the issue you are seeing.  For your specific case, you can

1. Remove inlining from the set of optimizations be performed.  You can use `-Oconfig=<file>` to set you optimizations.
1. Increase the max id bound, and run compact ids at the end: `--max-id-bound=0xFFFFFFFF -O --compact-ids`.

**Comment by s-perron** [comment] 2019-03-04 16:46
max-id-bound needs the number in decimal, and it must be a 32-bit unsigned value.

**Comment by s-perron** [comment] 2019-03-04 16:52
@alegal Then running compact-ids before-hand should solve the problem.  We do not do this by default because it renames all of the ids, which make it much more difficult to see how the optimizater changes things.  Add "--compact-ids -O", or the equivalent if you are using the API.

We have thought about how to make the optimizer smarter about reusing ids below the id bound that are not actually used, but we have not settled on a good way of doing it.  The cases we have come across can be easily solved by calling compact-ids before hand, so we have not had a lot of urgency in solving that problem.

**Comment by s-perron** [comment] 2019-03-05 19:43
I will assume there is a reasonable workaround for the specific issue.  The general problem will be track by https://github.com/KhronosGroup/SPIRV-Tools/issues/1841, so I will close this issue.

**Closed by s-perron** 2019-03-05 19:43 UTC
