### ISSUE TITLE
opt: dEQP-VK.graphicsfuzz.unreachable-continue-statement

### ISSUE THREAD

**Issue by paulthomson** [KhronosGroup/SPIRV-Tools#3041] opened 2019-11-11 21:46 UTC
This test fails. To reproduce: 

```
spirv-opt -O -o temp.spv *.spv
spirv-val temp.spv
```

[unreachable-continue-statement.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/3833352/unreachable-continue-statement.zip)

**Comment by s-perron** [comment] 2019-11-19 03:06
I cannot reproduce the problem.  @paulthomson Can you double check?

**Comment by ben-clayton** [comment] 2019-11-20 13:35
I have tried to reproduce this but I appear to get a failure only when assembling the shader from source.
I'm using 2ee9aaa288d91fbaec5bc51473169c079c764240:

```bash
> spirv-opt -O unreachable-continue-statement.variant_fragment_shader.frag.spv -o opt.spv
# No issues

> spirv-as unreachable-continue-statement.variant_fragment_shader.frag.asm -o shader.spv
> spirv-opt -O shader.spv -o opt.spv

error: line 39: Interface variable id <7> is used by entry point 'main' id <2>, but is not listed as an interface
  %_ = OpVariable %_ptr_Uniform_buf0 Uniform
```

If I use an old† prebuilt of `spirv-as` to assemble the shader, I see no errors when assembling. I've included the locally assembled `.spv` files with the old and new `spirv-as`. It appears the difference between these two outputs is the SPIR-V version (`1.3` vs `1.5`).

I suspect there is another issue (which is probably what @paulthomson was originally reporting), which I believe may be a dupe of b/144692525. I'll see if I can figure out how to reproduce that with the `1.3` version of this shader.

---

†: I have no idea what build this is, but I believe this was a prebuilt binary downloaded ~ July 2018.

**Comment by ben-clayton** [comment] 2019-11-20 14:13
The issue SwiftShader has with this particular shader is that the optimization passes are still outputting `OpReturnValue`, despite using the `-eliminate-dead-branches` pass.

If we append `--merge-return` to the list of optimization passes run by `-O`, we get a:
`error: line 0: Module contains unreachable blocks during merge return.  Run dead branch elimination before merge return.`, which sounds a lot like a dupe of b/144573625.

Adding yet another `--eliminate-dead-branches` before the final `--merge-return` also does not help.

**Comment by s-perron** [comment] 2019-11-20 14:32
This is because when you assemble the spir-v with spirv-as it default to the spv1.4 target environment, when the original code was written for spv1.[0123].  Add `--target-env spv1.0` to the command line when assembling.

**Comment by s-perron** [comment] 2019-11-20 14:39
If the problem is that the function is not being inlined, which is why the OpReturnValue remains, then I see the problem.  I can look into that.

**Comment by s-perron** [comment] 2019-11-20 14:44
@kuhar Can you take a look at why we are not inlining in this case?

**Comment by paulthomson** [comment] 2019-11-20 15:58
Oops sorry. You need to do:

```
spirv-opt -O --validate-after-all -o temp.spv *.spv
```

to get a validation error.

**Comment by kuhar** [comment] 2019-12-07 03:16
@paulthomson Is the input valid?

```
$ ../build-debug/tools/spirv-val unreachable-continue-statement.variant_fragment_shader.frag.spv               
error: line 65: Header block 41[%41] is contained in the loop construct headed by 33[%33], but it's merge block 35[%35] is not
  %41 = OpLabel
```

**Comment by s-perron** [comment] 2019-12-07 03:27
Duplicate of something that Alan fixed.  I forget the number.  When it was first opened the validator was saying it was legal when it is not.

**Closed by s-perron** 2019-12-07 03:27 UTC
