### ISSUE TITLE
Merge return producing a phi of pointers

### ISSUE THREAD

**Issue by alan-baker** [KhronosGroup/SPIRV-Tools#3266] opened 2020-03-31 20:09 UTC
```
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Fragment %2 "main" %3
               OpExecutionMode %2 OriginUpperLeft
               OpDecorate %3 Location 0
               OpMemberDecorate %_struct_4 0 Offset 0
               OpDecorate %_struct_4 Block
               OpDecorate %5 DescriptorSet 0
               OpDecorate %5 Binding 0
       %void = OpTypeVoid
          %7 = OpTypeFunction %void
      %float = OpTypeFloat 32
    %v2float = OpTypeVector %float 2
%_ptr_Function_v2float = OpTypePointer Function %v2float
         %11 = OpTypeFunction %v2float %_ptr_Function_v2float
    %v4float = OpTypeVector %float 4
%_ptr_Output_v4float = OpTypePointer Output %v4float
          %3 = OpVariable %_ptr_Output_v4float Output
    %float_1 = OpConstant %float 1
    %float_0 = OpConstant %float 0
         %16 = OpConstantComposite %v4float %float_1 %float_0 %float_0 %float_1
  %_struct_4 = OpTypeStruct %v2float
%_ptr_Uniform__struct_4 = OpTypePointer Uniform %_struct_4
          %5 = OpVariable %_ptr_Uniform__struct_4 Uniform
        %int = OpTypeInt 32 1
      %int_0 = OpConstant %int 0
       %uint = OpTypeInt 32 0
     %uint_1 = OpConstant %uint 1
%_ptr_Uniform_float = OpTypePointer Uniform %float
       %bool = OpTypeBool
         %24 = OpConstantComposite %v2float %float_1 %float_1
%_ptr_Function_float = OpTypePointer Function %float
      %false = OpConstantFalse %bool
          %2 = OpFunction %void None %7
         %27 = OpLabel
         %28 = OpVariable %_ptr_Function_v2float Function
               OpStore %28 %24
         %29 = OpFunctionCall %v2float %30 %28
               OpReturn
               OpFunctionEnd
         %30 = OpFunction %v2float None %11
         %31 = OpFunctionParameter %_ptr_Function_v2float
         %32 = OpLabel
               OpStore %3 %16
               OpBranch %33
         %33 = OpLabel
               OpLoopMerge %34 %35 None
               OpBranch %36
         %36 = OpLabel
         %37 = OpAccessChain %_ptr_Uniform_float %5 %int_0 %uint_1
         %38 = OpLoad %float %37
         %39 = OpFOrdLessThan %bool %38 %float_0
               OpSelectionMerge %40 None
               OpBranchConditional %39 %41 %35
         %41 = OpLabel
               OpReturnValue %24
         %40 = OpLabel
               OpUnreachable
         %35 = OpLabel
         %42 = OpAccessChain %_ptr_Function_float %31 %uint_1
         %43 = OpLoad %float %42
         %44 = OpFSub %float %43 %float_1
               OpStore %42 %44
               OpBranchConditional %false %33 %34
         %34 = OpLabel
         %45 = OpLoad %float %42
         %46 = OpFSub %float %45 %float_1
               OpStore %42 %46
               OpReturnValue %24
               OpFunctionEnd
```

Run `--merge-return` and validate the results. Should see the error:
>error: line 78: Using pointers with OpPhi requires capability VariablePointers or VariablePointersStorageBuffer
>  %58 = OpPhi %_ptr_Function_float %57 %41 %57 %40 %42 %35

Merge return is introducing a phi of Function scope pointers.  The validator message isn't great here (being improved in an open PR), but merge return shouldn't generate this code.

**Comment by paulthomson** [comment] 2020-04-03 10:18
Could be a dupe of #3030 ?

**Comment by alan-baker** [comment] 2020-04-03 12:40
Yeah, seems likely. There were three graphicsfuzz tests exposing this particular issue.

**Comment by c0d1f1ed** [comment] 2020-06-19 13:44
Friendly ping. This is the only thing preventing SwiftShader from passing dEQP 1.2.1.

**Closed** 2020-07-22 15:10 UTC
Labels: bug, component:optimization
