### ISSUE TITLE
Cannot compile as C library, has to be C++

### ISSUE THREAD

**Issue by httpdigest** [KhronosGroup/SPIRV-Tools#171] opened 2016-04-01 19:11 UTC
There is a tiny inconvenience in OpenCL.std.h included by libspirv.h. That OpenCL header file is a C++ header file and so a client including libspirv.h cannot compile as C application, but must use a C++ compiler. (msvc complains when compiling a .c file including `spirv-tools\libspirv.h`)
Simply guarding the "namespace" directive with an `#ifdef __cplusplus` , or removing that namespace declaration, helped.

**Comment by dekimir** [comment] 2016-04-01 19:31
The problem is upstream.  This file comes from the SPIR-V repo, and we've been reluctant to change it locally.

Keeping the issue open for now, until it's resolved.

See also #138.

**Comment by httpdigest** [comment] 2016-04-01 19:32
Oh, didn't see that. :)

**Comment by dekimir** [comment] 2016-04-01 19:38
Sorry about the problem persisting.  I've fixed our code when I closed #138, but it's still impossible to compile in C. :disappointed: 

We're hesitant to diverge `OpenCL.std.h` because it complicates upgrading from upstream.

@antiagainst: might #170 resolve this, do you think?

**Comment by httpdigest** [comment] 2016-04-01 19:42
It's really not a big thing for me. I simply patched my local repo version and will keep it at that.
It's not like the OpenCL.std.h is going to change frequently.
And if it is abount to change again, then maybe you guys could persuade Khronos to add a tiny little ifdef guard around it for the future? :)

**Comment by dekimir** [comment] 2016-04-01 19:57
Yes, we're working on having it fixed at the source.  And now that I've reviewed #170, I can confirm that it will remove all public-API dependence on upstream headers. :+1:

**Comment by antiagainst** [comment] 2016-04-01 20:17
@dekimir: Yeah. :) Sorry for the late reply. With #170, users of `libspirv.h` are free of upstream SPIR-V headers.

**Comment by antiagainst** [comment] 2016-04-04 14:55
Hi @httpdigest, #170 is merged so it should be able to compile as C library now. Thanks!

**Closed** 2016-04-04 14:56 UTC

**Comment by httpdigest** [comment] 2016-04-04 15:28
Hi @antiagainst, yes clients compile now fine using C-only. Thanks!
